name: istvan.barra
favicon: null
layout_spectrum: 0.40073604602366686
typography_spectrum: 0.15277755307033658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5713135530240834
  lightness: 0.6589491814374924
  saturation: 0.7650781939737499
  rhythmicContrast: 0.49585958383977413
purpose: []
